# Package 설치

!pip install pack명

### 데이터 자료변환
+ 범주형 자료 : 명목,순서
+ 수치형 자료 : 등간,비율
+ 나이는 수치형일수도 범주형일수도 있고 둘 다 아닐 수도 있다.
+ 1은 숫자로서의 1과 문자로서의 1로 나뉜다.
+ 데이터 형식이 중요함.
+ 글자 입력시 > ### 은 제목,+는 문단을 나눠줌

snake형식은 case_rule 이렇게 문자구분을 _ 로 해줌.
웬만하면 풀네임 그대로 적용하고 줄임말은 쓰지 말것.


### 숫자열 자료형

#### 덧셈과 뺄셈

In [6]:
a = 11
b = 5
print(a+b)
print(type(a+b))

16
<class 'int'>


#### 곱셈과 나눗셈과 제곱

In [7]:
a = 10
b = 3
print(a*b)
print(a/b)
print(a**b)

30
3.3333333333333335
1000


#### 몫과 나머지 구하기

In [8]:
a=10
b=3
print(a//b)
print(a%b)

3
1


### 문자열 자료형

In [9]:
type('Hello')

str

In [10]:
type("that's good")

str

In [11]:
type('he said "i go school"')

str

+ 문자열에서 "이나 '은 같은 역할이지만 문자열안에 같은 ' 나 "가 있을경우 나머지하나로 번갈아가면서 사용
+ 또는 \을 사용하여 문자임을 표시

In [12]:
print('Hello \n \t \'World\' \n')

Hello 
 	 'World' 



## 문자열의 사칙연산

In [13]:
a='백견이'
b='불여일타'
print(a+b)

백견이불여일타


In [16]:
c='영차'
print(c*2)
print(c*10)

영차영차
영차영차영차영차영차영차영차영차영차영차


In [17]:
string_ = 'Data science Camp'
len(string_)

17

In [19]:
string_[0]

'D'

In [23]:
string_[-1]

'p'

In [25]:
string_[0:1]

'D'

In [26]:
string_[5::]

'science Camp'

+ len은 문자열의 길이를 알려줌
+ string_[n]은 n번째 글자를 나타냄 파이썬은 0부터 시작함
+ -1은 마지막 문자를 출력함
+ :을 사용하면 구간을 나타냄 5::는 6번째부터 끝까지 나타내고 ::5는 처음부터 5번째까지 나타냄

## 리스트 자료형

S V M L D 순서 스칼라 벡터 매트릭스 리스트 데이터프레임

In [6]:
d = [0,1,'data','science']
e = [2,0,['too','easy']]
print(d, '\n')
print(e, '\n')

[0, 1, 'data', 'science'] 

[2, 0, ['too', 'easy']] 



In [38]:
list_=['data','science',101,'camp']
len(list_)
print(list_[1:3],'\n')

['science', 101] 



+ [1:3]은 2번째 3번째

#### 리스트 정렬 : sort
+ 정렬을 하고나서 group by정도는 해봐라. 멀티솔트가 group by

In [42]:
list_=[2,1,3,4]

In [44]:
list_.sort()
print(list_)

[1, 2, 3, 4]


In [46]:
list_.sort(reverse=True)
print(list_)

[4, 3, 2, 1]


### 딕셔너리 자료형

+ 키와 벨류를 이용한것이 딕셔너리 자료형

In [51]:
dic = {'name':'IU','age':27,'인기곡':['좋은날','마쉬멜로우','금요일에 만나요',23]}
print(type(dic))

<class 'dict'>


In [54]:
dic['인기곡']

['좋은날', '마쉬멜로우', '금요일에 만나요', 23]

In [58]:
def add(a,b):
    return(a+b)

In [62]:
c=add(5,7)
print(c)

12


In [63]:
def shout():
    print('야호'*10)

In [64]:
shout()

야호야호야호야호야호야호야호야호야호야호


## 조건문

+ 들여쓰기가 중요!
+ x>y x가 y보다 클때 true,그 외에는 false
+ x>=y x가 y보다 크거나같을때 true, 그 외에는 fasle
+ x==y x가 y와 같을때 true,그 외에는 false
+ x!=y x가 y가 다를때 true,그 외네는 false 

In [66]:
season='겨울'

if season =='겨울':
    print('현금을 가지고 다녀라')
else:
    print('현금 소지는 자유다')

현금을 가지고 다녀라


In [75]:
man='유승우'

if man=='전태양':
    print(201552043)
elif man=='한현수':
    print(201552013)
else:
    print(201552001)

201552001


In [76]:
button = 3

if button == 1:
    print('레츠비')
elif button ==2:
    print('웰치스')
elif button ==3:
    print('코카콜라')
else:
    print('제공하지 않는 음료')

코카콜라


In [77]:
'D'in'Dacon'

True

## 반복문 For&While

In [81]:
sum1 = 0
for i in [1,2,3,4,5,6,7,8,9,10]:
    sum1 += i
print(sum1)

55


In [82]:
sum2 = 0
for i in range(1,11):
    sum2 += i
print(sum2)

55


In [86]:
for i in ['햄버거','피자','치킨']:
    print('나는', i, '가 먹고 싶다')
    


나는 햄버거 가 먹고 싶다
나는 피자 가 먹고 싶다
나는 치킨 가 먹고 싶다


In [87]:
i=0
while i <=5:
    print('붕어빵',i,'마리')
    i+=1

붕어빵 0 마리
붕어빵 1 마리
붕어빵 2 마리
붕어빵 3 마리
붕어빵 4 마리
붕어빵 5 마리


In [89]:
coke=5

while True:
    print('콜라를 줍니다.')
    coke-=1
    if coke==0:
        print('콜라가 다떨어졌습니다')
        break
        

콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라가 다떨어졌습니다


In [1]:
coke = 10
money = 5000

while True:
    if money == 700:
        print('콜라를 줍니다. 거스름돈은 0원 입니다.')
        coke = coke -1
        money -=700
    elif money > 700:
        print('콜라를 줍니다')
        coke = coke-1
        money -= 700
    else:
        print('거스름돈은',money-700,'입니다','콜라가 다 떨어졌습니다')
        print('판매를 중지합니다.')
        break
    if coke == 0:
        print('거스름돈은',money-700,'입니다','콜라가 다 떨어졌습니다')
        print('판매를 중지합니다.')
        break

콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
콜라를 줍니다
거스름돈은 -600 입니다 콜라가 다 떨어졌습니다
판매를 중지합니다.


# NUMPY

In [2]:
import numpy as np
np_vector = np.array([1,2,3,4], dtype=np.int)
print(np_vector)

[1 2 3 4]


In [3]:
[np_vector.shape, np_vector.size, np_vector.dtype, np_vector.ndim]

[(4,), 4, dtype('int32'), 1]

In [6]:
np_matrix=np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],dtype = np.int64)
[np_matrix.shape, np_matrix.size, np_matrix.dtype, np_matrix.ndim]

[(3, 4), 12, dtype('int64'), 2]

In [7]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.random.uniform(0, 1, 10)

array([0.05553264, 0.23203766, 0.06596688, 0.19229039, 0.76148831,
       0.96935869, 0.74587279, 0.15420508, 0.36044826, 0.29078059])

In [11]:
np_vector = np.arange(1,13, dtype = np.int)

In [12]:
np_vector < 9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False])

In [13]:
np_vector[np_vector < 9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]], dtype = np.int)
np_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
np_matrix[[1, 2, 1], [0, 2, 3]]

array([ 5, 11,  8])

In [16]:
np_matrix.sum(axis = 0)

array([15, 18, 21, 24])

In [17]:
np_matrix.sum(axis = 1)

array([10, 26, 42])

In [18]:
np_vector.mean()

6.5